# Generated by Django 2.2.6 on 2020-04-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0006_images_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='fileName',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
