# Generated by Django 3.0.5 on 2020-04-09 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searchEngine', '0007_auto_20200405_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownImages', to=settings.AUTH_USER_MODEL),
        ),
    ]
