# Generated by Django 3.0.5 on 2020-04-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0008_auto_20200409_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='owner',
        ),
    ]
