# Generated by Django 3.0.5 on 2020-04-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0009_remove_images_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
