# Generated by Django 3.0.5 on 2020-04-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tag', models.TextField(unique=True)),
            ],
        ),
    ]
