# Generated by Django 2.2.6 on 2020-03-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memes',
            name='title',
        ),
        migrations.AddField(
            model_name='memes',
            name='imageDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memes',
            name='textDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
