# Generated by Django 2.2.6 on 2020-03-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_auto_20200317_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='memes',
            name='fileName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memes',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
