# Generated by Django 3.0.4 on 2020-03-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_auto_20200325_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='memes',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
