# Generated by Django 3.0.5 on 2020-04-09 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memes', '0004_auto_20200324_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='memes',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownImages', to=settings.AUTH_USER_MODEL),
        ),
    ]
