# Generated by Django 3.0.5 on 2020-04-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_memes_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='memes',
            name='is_mark_up_added',
            field=models.NullBooleanField(),
        ),
    ]
