# Generated by Django 3.0.5 on 2020-04-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0007_auto_20200410_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memes',
            name='owner',
        ),
    ]
