# Generated by Django 3.0.5 on 2020-04-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('memes', '0010_auto_20200410_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='memes',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='taggedMemes', to='tags.Tags'),
        ),
    ]
