# Generated by Django 3.0.5 on 2020-04-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0012_auto_20200415_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='memes',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memes',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
