# Generated by Django 3.0.5 on 2020-04-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0013_auto_20200423_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='memes',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memes',
            name='ratio',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='memes',
            name='time',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
