# Generated by Django 2.2.6 on 2020-03-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Email', models.TextField()),
            ],
        ),
    ]
